### ISSUE TITLE
Error occurs when execute command "import geocat.datafiles as gdf"

### ISSUE THREAD

**Issue by yang7ke** [NCAR/GeoCAT-examples#295]
Hi
I failed to  run command "import **geocat.datafiles** as gdf". And other commands like "from netCDF4 import Dataset", "from wrf import (getvar, to_np, latlon_coords, get_cartopy)" show no error.
Any comments would be appreciated, thanks in advance!

PS:
I have finished the Installation without any error, i.e, Create a GeoCAT-examples Conda environment  under the guidance of website (https://geocat-examples.readthedocs.io/en/latest/install.html)

**Running reports:**

**(geocat-examples) yang7kewu@Yang7keWu-YangTianT4900d-00:~/UbuntuFiles531G$ python**
Python 3.7.8 | packaged by conda-forge | (default, Nov 17 2020, 23:45:15) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
 from netCDF4 import Dataset
 import numpy as np
 import matplotlib.pyplot as plt
 import matplotlib.ticker as mticker
 import cartopy.crs as ccrs
 from cartopy.feature import NaturalEarthFeature
 from wrf import (getvar, to_np, latlon_coords, get_cartopy)
 **import geocat.datafiles as gdf**
Traceback (most recent call last):
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdab9488150>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /NCAR/GeoCAT-datafiles/master/registry.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdab9488150>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/geocat/datafiles/__init__.py", line 28, in <module>
    _update_registry(POOCH)
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/geocat/datafiles/__init__.py", line 18, in _update_registry
    new_sha256 = hashlib.sha256(requests.get(p.get_url("registry.txt")).content).hexdigest()
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/yang7kewu/miniconda2/envs/geocat-examples/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /NCAR/GeoCAT-datafiles/master/registry.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdab9488150>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by erogluorhan** [comment]
Hi @yang7ke 

I am sorry to hear the inconveniences you had. 

I can see from your outputs that your `miniconda` version is `miniconda2`, which is the version for `Python=2.7`. However, your `geocat-examples` environment is having `Python=3.7`.  I would first like you to migrate to `miniconda3` in your local and give another try to `GeoCAT-examples`. In the meantime, could you also paste the output of `conda list` command when your `geocat-examples` environment is active?

Thanks!

Orhan - GeoCAT

**Comment by yang7ke** [comment]
Hi @erogluorhan 

Thanks for your reply.

It seems that I made a mistake about version mismatch. Now I have installed `Miniconda3`, and I removed the entire `Miniconda2` install directory. But this time I fail to create a `geocat-examples conda` environment. The running reports of establishing `geocat-examples` environment are shown in the followings, and the output of `conda list` command is also pasted in the end that you may appreciate.

Looking forward to your help!
Yang7ke

yang7kewu@Yang7keWu-YangTianT4900d-00:~/UbuntuFiles531G$ **`conda env create -f conda_environment.yml -n geocat-examples`**
Solving environment: failed

ResolvePackageNotFound: 
  - geocat-comp=0.2
  - geocat-ncomp
  - wrf-python
  - matplotlib=3.3.0
  - libncomp=0.2
  - metpy
  - matplotlib-base[version='>=2.1.0']
  - geocat-ncomp=0.2

yang7kewu@Yang7keWu-YangTianT4900d-00:~/UbuntuFiles531G$ **`conda create -c conda-forge -c ncar -n geocat-examples python=3 geocat-comp geocat-datafiles geocat-viz=2020.2.18.1 netcdf4 matplotlib cartopy jupyter`**
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - geocat-comp
  - geocat-ncomp

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/ncar/linux-32
  - https://conda.anaconda.org/ncar/noarch
  - https://repo.anaconda.com/pkgs/main/linux-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-32
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


yang7kewu@Yang7keWu-YangTianT4900d-00:~/UbuntuFiles531G$ **`conda list`**
packages in environment at /home/yang7kewu/miniconda3:

Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0  
ca-certificates           2018.03.07                    0  
certifi                   2018.11.29               py37_0  
cffi                      1.11.5           py37he75722e_1  
chardet                   3.0.4                    py37_1  
conda                     4.5.12                   py37_0  
conda-env                 2.6.0                         1  
cryptography              2.4.2            py37h1ba5d50_0  
idna                      2.8                      py37_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                h97ff0df_4  
libgcc-ng                 8.2.0                h9268252_1  
libstdcxx-ng              8.2.0                h9268252_1  
ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1a               h7b6447c_0  
pip                       18.1                     py37_0  
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pyopenssl                 18.0.0                   py37_0  
pysocks                   1.6.8                    py37_0  
python                    3.7.1                h0371630_7  
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py37_0  
ruamel_yaml               0.15.46          py37h14c3975_0  
setuptools                40.6.3                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.26.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
urllib3                   1.24.1                   py37_0  
wheel                     0.32.3                   py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                h69be6c5_2  
zlib                      1.2.11               h7b6447c_3

**Comment by erogluorhan** [comment]
@yang7ke , thanks a lot for the detailed information!

I gave it a fresh try in both Mac and Linux environments, and there does not seem to be an actual installation issue. I have a few questions and recommendations though:

1. Is your Ubuntu an older 32-bit version? If so, it might be the reason that the current package files from Anaconda did not work for your OS.

2. Your conda version seems to be 4.5.12, please run the following command to upgrade to the latest one:

`conda update conda`

and then give another try to the following code (which is a slightly modified version of what you provided to me, due to a strange conda behavior recently):

`conda create -c conda-forge -c ncar -n geocat-examples python=3 geocat-comp=0.2 geocat-ncomp=0.2 libncomp=0.2 geocat-datafiles geocat-viz=2020.2.18.1 netcdf4 matplotlib cartopy jupyter`

I hope these help; please let me know.

Best,

Orhan - GeoCAT

**Comment by yang7ke** [comment]
@erogluorhan ,thanks for your further suggestions!

I am sorry to tell you that I still can not make it. I guest the reason is that there is a firewall to protect our country (china) Net, thus sometimes we are unable to reach some international network resources. Connecting to our campus VPN might help a little, but  not always. For instance, we can not use search engines like Google (even under VPN).

Anyway, the running reports based on your suggestions will also be listed in the followings:

1. My Ubuntu is 64-bit version. 

2. After I run the command **`conda update conda`**
The following packages were updated:
```
    asn1crypto:    0.24.0-py37_0     --> 1.4.0-py_0            
    certifi:       2018.11.29-py37_0 --> 2020.6.20-pyhd3eb1b0_3
    idna:          2.8-py37_0        --> 2.10-py_0             
    pycparser:     2.19-py37_0       --> 2.20-py_2             
    requests:      2.21.0-py37_0     --> 2.25.0-pyhd3eb1b0_0   
    six:           1.12.0-py37_0     --> 1.15.0-py_0           
    wheel:         0.32.3-py37_0     --> 0.36.1-pyhd3eb1b0_0  
``` 
Apparently, `conda` is not included above, the `conda` version is still 4.5.12 and I confirm this by command `conda list`.

The result of your suggested  creating  `geocat-examples` environment code is:
(base) yang7kewu@Yang7keWu-YangTianT4900d-00:~/UbuntuFiles531G$ **`conda create -c conda-forge -c ncar -n geocat-examples python=3 geocat-comp=0.2 geocat-ncomp=0.2 libncomp=0.2 geocat-datafiles geocat-viz=2020.2.18.1 netcdf4 matplotlib cartopy jupyter`**
```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - geocat-ncomp=0.2
  - geocat-comp=0.2
  - geocat-ncomp
  - libncomp=0.2

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/ncar/linux-32
  - https://conda.anaconda.org/ncar/noarch
  - https://repo.anaconda.com/pkgs/main/linux-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-32
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by erogluorhan** [comment]
@yang7ke 

I am sorry to hear the inconveniences you are still having! I agree with you that it is highly likely due to internet policies you pointed out. The outputs of you conda environment installation command run look like you are blocked to use [NCAR's Anaconda channel](https://anaconda.org/NCAR), which you may want to resolve.

I hope you can resolve your problems.

Thanks!

**Comment by yang7ke** [comment]
@erogluorhan 

Thanks all your patience. 
Maybe I need to **manually**  create the conda enviroment. And it it seems these dependencies could be download from **GitHub**. I will give it a try following your packages catalog, e.g., [NCAR's Anaconda channel ](https://anaconda.org/NCAR/repo).
I would love to share my install experience if I could make it, and hope to help someone else.

Best wishes!

yang7ke

**Comment by andersy005** [comment]
@yang7ke, The fact that conda is listing `linux-32` in your list of channels is a sign that the issue is a platform mismatch and not an internet access policy, what is the output of `conda info`?

**Comment by yang7ke** [comment]
@erogluorhan 

Hi, the output of `conda info` lists here (a try in another laptop displayed in the followings):
```
     active environment : base
    active env location : /home/yang7kewu/miniconda3
            shell level : 1
       user config file : /home/yang7kewu/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/yang7kewu/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-32
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/yang7kewu/miniconda3/pkgs
                          /home/yang7kewu/.conda/pkgs
       envs directories : /home/yang7kewu/miniconda3/envs
                          /home/yang7kewu/.conda/envs
               platform : linux-32
             user-agent : conda/4.5.12 requests/2.25.0 CPython/3.7.1 Linux/5.0.0-38-generic ubuntu/19.04 glibc/2.29
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Another Try**
Since you suggests that is issue about platform mismatch, then I try to install `geocat-examples` in another laptop. Unfortunately, just like my first comment, error occurs when execute command `import geocat.datafiles as gdf`. It seems the package `geocat.datafiles` has its unique usage requirements. And other commands like `from netCDF4 import Dataset`, `from wrf import (getvar, to_np, latlon_coords, get_cartopy)` also works fine this time. I also paste the output of `conda info` and running reports here:
```
(base) yangqike@yangqike-Lenovo-G50-80m:~$ conda info

     active environment : base
    active env location : /home/yangqike/miniconda3
            shell level : 1
       user config file : /home/yangqike/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/yangqike/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/yangqike/miniconda3/pkgs
                          /home/yangqike/.conda/pkgs
       envs directories : /home/yangqike/miniconda3/envs
                          /home/yangqike/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/4.15.0-126-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

(base) yangqike@yangqike-Lenovo-G50-80m:~$ conda activate geocat-examples
(geocat-examples) yangqike@yangqike-Lenovo-G50-80m:~$ python
Python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 21:08:20) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> the output of `conda info` lists here 
KeyboardInterrupt
>>> from netCDF4 import Dataset
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> import xarray as xr
>>> import os
>>> 
>>> from wrf import (to_np, getvar, CoordPair, vertcross, latlon_coords)
>>> import geocat.datafiles as gdf
Traceback (most recent call last):
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fec3997dd90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /NCAR/GeoCAT-datafiles/master/registry.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fec3997dd90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/geocat/datafiles/__init__.py", line 28, in <module>
    _update_registry(POOCH)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/geocat/datafiles/__init__.py", line 18, in _update_registry
    new_sha256 = hashlib.sha256(requests.get(p.get_url("registry.txt")).content).hexdigest()
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /NCAR/GeoCAT-datafiles/master/registry.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fec3997dd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
>>> import geocat.viz.util as gvutil
>>> 

```

**Comment by andersy005** [comment]
This _new_ laptop appears to be linux-64 bit based (which is what you want)

```bash
envs directories : /home/yangqike/miniconda3/envs
                          /home/yangqike/.conda/envs
               platform : linux-64
```

Regarding the `Failed to establish a new connection: [Errno 111] Connection refused'` error. You are right about this being a connectivity issue. Does the following code snippet work on your _new_ laptop?


```python
In [11]: import requests

In [12]: url = 'https://github.com/NCAR/GeoCAT-datafiles/raw/master/registry.txt'

In [13]: requests.get(url)
Out[13]: <Response [200]>
```

**Comment by yang7ke** [comment]
Hi, the same error as executing code `import geocat.datafiles as gdf` occurs, you can see it in the followings. And I am also unable to connect your given web site `https://github.com/NCAR/GeoCAT-datafiles/raw/master/registry.txt` in the browser. Then I try `https://github.com/NCAR/GeoCAT-datafiles/raw` (the parent directory), it shows  `404 This is not the web page you are looking for`.

```
(geocat-examples) yangqike@yangqike-Lenovo-G50-80m:~$ python
Python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 21:08:20) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> url = 'https://github.com/NCAR/GeoCAT-datafiles/raw/master/registry.txt'
>>> requests.get(url)
Traceback (most recent call last):
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f291b0b0390>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /NCAR/GeoCAT-datafiles/master/registry.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f291b0b0390>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/yangqike/miniconda3/envs/geocat-examples/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /NCAR/GeoCAT-datafiles/master/registry.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f291b0b0390>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by kozacy** [comment]
Hi, I met same problem with you, have you solved the problem?

Thank you!

**Comment by erogluorhan** [comment]
Hi @yang7ke  and @kozacy 

The issue with `geocat.datafiles` is due to the release of its newer version (which is based on renaming of the directory/branch "master" to "main"). Please try to update your geocat-datafiles package to ` v2021.1.0` in your environment or if it does not work, recreate your `geocat-examples` environment.

**Comment by erogluorhan** [comment]
Hi @yang7ke and @kozacy

Is there any update on this, one way or the other?
