### ISSUE TITLE
Upstream CI failures

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/geocat-examples#620]
We have several [failures right now in Upstream CI](https://github.com/NCAR/geocat-examples/actions/runs/11309711646/job/31453839654).  It's looks like they're coming from Matplotlib updates.

In particular the following examples are impacted:
* NCL_xy_16.py
* NCL_overlay_11b.py
* NCL_hov_3.py
* NCL_coneff_11.py

<details>
<summary>Log</summary>
Unexpected failing examples (4):

    ../Gallery/XY/NCL_xy_16.py failed leaving traceback:

    Traceback (most recent call last):
      File "/home/runner/work/geocat-examples/geocat-examples/Gallery/XY/NCL_xy_16.py", line 102, in <module>
        plt.legend(handles,
      File "/home/runner/micromamba/envs/geocat-examples/lib/python3.11/site-packages/matplotlib/pyplot.py", line 3593, in legend
        return gca().legend(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/micromamba/envs/geocat-examples/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 335, in legend
        self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/micromamba/envs/geocat-examples/lib/python3.11/site-packages/matplotlib/legend.py", line 462, in __init__
        if len(handles) < 2:
           ^^^^^^^^^^^^
    TypeError: object of type 'list_reverseiterator' has no len()

    ../Gallery/Overlays/NCL_overlay_11b.py failed leaving traceback:

    Traceback (most recent call last):
      File "/home/runner/work/geocat-examples/geocat-examples/Gallery/Overlays/NCL_overlay_11b.py", line 185, in <module>
        for col in cf.collections:
                   ^^^^^^^^^^^^^^
    AttributeError: 'GeoContourSet' object has no attribute 'collections'

    ../Gallery/Contours/NCL_hov_3.py failed leaving traceback:

    Traceback (most recent call last):
      File "/home/runner/work/geocat-examples/geocat-examples/Gallery/Contours/NCL_hov_3.py", line 52, in <module>
        for i, collection in enumerate(cf.collections):
                                       ^^^^^^^^^^^^^^
    AttributeError: 'QuadContourSet' object has no attribute 'collections'

    ../Gallery/Contours/NCL_coneff_11.py failed leaving traceback:

    Traceback (most recent call last):
      File "/home/runner/work/geocat-examples/geocat-examples/Gallery/Contours/NCL_coneff_11.py", line 62, in <module>
        for i, collection in enumerate(p.collections):
                                       ^^^^^^^^^^^^^
    AttributeError: 'QuadContourSet' object has no attribute 'collections'

-------------------------------------------------------------------------------
</details>

**Comment by kafitzgerald** [comment]
I suspect it's because of these changes:
* ContourSet moving to a single Collection - https://matplotlib.org/devdocs/api/next_api_changes/removals/28767-REC.html
* A deprecation or something related to this feature- https://github.com/matplotlib/matplotlib/pull/24759

**Comment by kafitzgerald** [comment]
This is blocked while we wait for the Matplotlib fix for different colored hatching to be backported to v3.9.x.

**Comment by kafitzgerald** [comment]
It looks like like I missed the usage of `collections` in NCL_hov_3.py here:
https://github.com/NCAR/geocat-examples/blob/1431c482ce1d451c412c0799b957f07e6a781782/Gallery/Contours/NCL_hov_3.py#L77

That can get fixed along with the hatching and linewidth items below after the Matplotlib 3.9.3 release
https://github.com/NCAR/geocat-examples/blob/1431c482ce1d451c412c0799b957f07e6a781782/Gallery/Contours/NCL_coneff_11.py#L62-L64

**Comment by kafitzgerald** [comment]
Looks like the matplotlib 3.9.3 release is out 🎉 so we should be able to more easily / robustly fix the rest of this.
